<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <PackageIcon>aws.png</PackageIcon>
    <ApplicationIcon>amazon_aws_logo_icon_145507.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="aws.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="amazon_aws_logo_icon_145507.ico" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="aws.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AWSSDK.Core" Version="4.0.0.24" />
    <PackageReference Include="AWSSDK.EC2" Version="4.0.31.1" />
    <PackageReference Include="AWSSDK.Route53" Version="4.0.2.8" />
    <PackageReference Include="AWSSDK.S3" Version="4.0.6.8" />

    <PackageReference Include="AWSSDK.RDS" Version="4.0.5.4" />
    <PackageReference Include="AWSSDK.AutoScaling" Version="4.0.2.10" />
    <PackageReference Include="AWSSDK.SecurityToken" Version="4.0.2" />
    <PackageReference Include="AWSSDK.SimpleSystemsManagement" Version="4.0.2.10" />
    <PackageReference Include="AWSSDK.SSO" Version="4.0.0.20">
      <TreatAsUsed>true</TreatAsUsed>
    </PackageReference>
    <PackageReference Include="AWSSDK.SSOOIDC" Version="4.0.0.20">
      <TreatAsUsed>true</TreatAsUsed>
    </PackageReference>
    <PackageReference Include="MaterialDesignThemes" Version="5.2.1">
      <TreatAsUsed>true</TreatAsUsed>
    </PackageReference>
    <PackageReference Include="Microsoft-WindowsAPICodePack-Shell" Version="1.1.5" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135">
      <TreatAsUsed>true</TreatAsUsed>
    </PackageReference>

  </ItemGroup>
  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <None Update="aws.ico">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
</Project>
